### PR TITLE
👮🏽 Rubocop config 👮🏽 #484

### LINKED ISSUE #484: 👮🏽 Rubocop config 👮🏽
Screen Shot 2020-05-31 at 1 55 10 am

### PR DESCRIPTION
**Pull request by tHe-AK**
Fixes #484

### CODE REVIEW

**Review by jbampton — CHANGES_REQUESTED** [review]
https://app.circleci.com/pipelines/github/slurpcode/slurp/1686/workflows/fc9fa447-1a8d-45f9-8146-a02978f9302a/jobs/6327  Seems we have a new word to add to our dictionary "dependabot".  

You need to add another commit and add the word to -> https://github.com/slurpcode/slurp/blob/master/.aspell.en.pws 
and update the first line to 315

**Comment by tHe-AK** [comment]
> https://app.circleci.com/pipelines/github/slurpcode/slurp/1686/workflows/fc9fa447-1a8d-45f9-8146-a02978f9302a/jobs/6327 Seems we have a new word to add to our dictionary "dependabot".
> 
> You need to add another commit and add the word to -> https://github.com/slurpcode/slurp/blob/master/.aspell.en.pws
> and update the first line to 315

'Dependabot' is already present in [.aspell.en.pws](https://github.com/slurpcode/slurp/blob/1ac28112c8e899d1f13a82f3aa871bff8dc63b19/.aspell.en.pws#L34). I guess, We have to update [check-spelling.sh](https://github.com/slurpcode/slurp/blob/master/check-spelling.sh) for case insensitive check.

**Comment by jbampton** [comment]
Yeah I know all about the dictionary problems.  

https://github.com/slurpcode/slurp/issues/600  is the Decemeber code sprint and this PR is the first to get in.

This is part of the larger overall issue #600 

We need figure it out

**Review by FerdinaKusumah — APPROVED** [review]

**Review by FerdinaKusumah — APPROVED** [review]

**Review by jbampton — CHANGES_REQUESTED** [review]
Looks like this is not done properly.  I can remove cops from `.rubocop.yml` that you added etc.  Some we don't need at all.

For example you can remove:

Screen Shot 2020-12-04 at 7 24 10 pm

**Comment by jbampton** [comment]
You would normally disable a cop, or set its style when it produces an error or fix the issue.

For example as shown in the image:

Screen Shot 2020-12-04 at 7 40 17 pm

**Pull request closed without merging**
