### PR TITLE
5 docs - 3 maths and 2 standard

### PR DESCRIPTION
**Pull request by HadeerAIA**
Please, check these files...

### CODE REVIEW

**Comment by BaseMax** [comment]
Hi, can you introduce yourself?

**Comment by HadeerAIA** [comment]
> Hi, can you introduce yourself?

Hi, I'm Hadeer Elfiky, freelancer from Upwork.

**Review by ayushrana182 — COMMENTED** [review]
Shouldn't pre-commit be passing all the tests?

**Comment by HadeerAIA** [comment]
> Shouldn't pre-commit be passing all the tests?

I have tried to do it, But it throws me that error when I run "pre-commit run --all-files"

An unexpected error has occurred: CalledProcessError: command: ('rbenv', 'init', '-')
return code: 1
expected return code: 0
stdout:
    Executable `bash` not found
stderr: (none)

**Review by jbampton — APPROVED** [review]

**Pull request merged**
