### PR TITLE
Add another doc: DESCRIPTIVE STATISTICS #2128

### PR DESCRIPTION
**Pull request by aaftab1441**

### CODE REVIEW

**Review by jbampton — CHANGES_REQUESTED** [review]
pre-commit failed

https://github.com/slurpcode/slurp/actions/runs/4569684065/jobs/8066197249?pr=2136

**Comment by jbampton** [comment]
https://pre-commit.com/

**Comment by jbampton** [comment]
Super-Linter failed:

https://github.com/slurpcode/slurp/actions/runs/4569684059/jobs/8066197077?pr=2136

**Comment by BaseMax** [comment]
what's up here?

**Review by jbampton — CHANGES_REQUESTED** [review]
You need to add a menu item for the document in `index.rst`

Also a lot of the content is not marked up correctly.  See here:

https://slurp--2136.org.readthedocs.build/en/2136/descriptive-statistics.html

**Comment by BaseMax** [comment]
What is new in this pr?

**Pull request merged**
