### PR TITLE
added lite version for salary 

### LINKED ISSUE #2794: Create new seek "lite" version -> no "salary" or "content" columns; don't open and crawl the full job ad
We already have a lite version so now we need to enhance it.

Lite version should not contain "salary" or "content".

So don't open the full job ad; Move the "check for lite logic" higher up, outside and above: `ad = agent.get(url)`

https://github.com/slurpcode/slurp/blob/e4813ef8a7f9c0cf1a944f17782a289a295f9f87/seek/seek.rb#L276

This will make the lite version faster to crawl

### PR DESCRIPTION
**Pull request by Dxuian**
resolves #2794 
image

### CODE REVIEW

**Comment by Dxuian** [comment]
fixed rubocop issues

**Comment by Dxuian** [comment]
@johnbampton  please review and merge 🙏🙏🙏🙏

**Comment by Dxuian** [comment]
@jbampton  any changes ? can we merge and close ?

**Comment by Dxuian** [comment]
@jbampton any changes ?

**Review by jbampton — APPROVED** [review]

**Comment by jbampton** [comment]
Thanks mate !!

**Pull request merged**
