### PR TITLE
 Issue: #780 Fix 'scrapers/python/scrapy/github/spider.py'. It scrapes 5 stats from github

### PR DESCRIPTION
**Pull request by ihasidul**
- Completed the scraper which scrapes 5 stats from the GitHub profile page.
The stats it grabs are:
        - Stars
        - Followers
        - Following
        - Repositories
        - Contributions in the last year
- Add pycache folder generated by the scraper to gitignore.

### CODE REVIEW

**Comment by jbampton** [comment]
https://app.circleci.com/pipelines/github/slurpcode/slurp/4909/workflows/1519c2fb-4c5d-46a5-b7bb-ae9e70eef487/jobs/31498

**Comment by ihasidul** [comment]
> https://app.circleci.com/pipelines/github/slurpcode/slurp/4909/workflows/1519c2fb-4c5d-46a5-b7bb-ae9e70eef487/jobs/31498

Should I fix this and push again?

**Comment by ihasidul** [comment]
@jbampton

**Comment by jbampton** [comment]
Yes it's from the "build" step here.  Needs fixing

**Comment by jbampton** [comment]
https://deepsource.io/gh/slurpcode/slurp/run/1952713c-9a38-4fb5-a113-d85aa5292a14/python/

**Comment by ihasidul** [comment]
@jbampton Need insights on how to handle this.

**Review by jbampton — APPROVED** [review]

**Pull request merged**
