### PR TITLE
XML parse fix

### PR DESCRIPTION
**Pull request by smriad**

### CODE REVIEW

**Review by BaseMax — DISMISSED** [review]
ok

**Review by jbampton — CHANGES_REQUESTED** [review]
You need to revert the file mode changes.  See `chmod` on Nix like systems

Screen Shot 2022-04-09 at 1 55 00 am
s

**Comment by smriad** [comment]
> You need to revert the file mode changes. See `chmod` on Nix like systems
> 
> Screen Shot 2022-04-09 at 1 55 00 am
> 
> s

PR updated

**Comment by BaseMax** [comment]
`.xsd`?

**Comment by smriad** [comment]
> > You need to revert the file mode changes. See `chmod` on Nix like systems
> > Screen Shot 2022-04-09 at 1 55 00 am
> > s
> 
> PR updated



> What is this binary file ?
> 
> Screen Shot 2022-04-09 at 2 25 41 am

https://github.com/slurpcode/slurp/blob/ce53c733aaefdcd735f814e98bb49cd6fe152682/charts/data/schema/concept.xsd

**Comment by BaseMax** [comment]
good

**Comment by BaseMax** [comment]
This branch is out-of-date with the base branch
Merge the latest changes from master into this branch.

**Pull request closed without merging**
