### PR TITLE
fixed gofpdf version

### PR DESCRIPTION
**Pull request by wickedknock**

### CODE REVIEW

**Review by jbampton — COMMENTED** [review]
It works with version 2 so why do we want to change this ?

**Comment by wickedknock** [comment]
> It works with version 2 so why do we want to change this ?

image

**Comment by jbampton** [comment]
https://pkg.go.dev/github.com/jung-kurt/gofpdf/v2

**Comment by wickedknock** [comment]
> https://pkg.go.dev/github.com/jung-kurt/gofpdf/v2

strange but github.com/jung-kurt/gofpdf  is being used instead of /v2 in all examples on official repo

**Comment by jbampton** [comment]
The auto bots wanted to update it.  Perhaps that is where the idea came from ?

https://github.com/slurpcode/slurp/pull/1978/files

**Comment by jbampton** [comment]
https://github.com/jung-kurt/gofpdf/tree/v2

v2 branch :)

**Comment by wickedknock** [comment]
> https://github.com/jung-kurt/gofpdf/tree/v2
> 
> v2 branch :)

This repository has been archived by the owner on Nov 14, 2021. It is now read-only.

**Pull request closed without merging**
