### PR TITLE
add anderson_darling_test.md file

### PR DESCRIPTION
**Pull request by HadeerAIA**

### CODE REVIEW

**Review by BaseMax — DISMISSED** [review]
LGTM

**Review by jbampton — CHANGES_REQUESTED** [review]
https://slurp--1315.org.readthedocs.build/en/1315/anderson_darling_test.html

Some of the images are broken

**Comment by HadeerAIA** [comment]
> https://slurp--1315.org.readthedocs.build/en/1315/anderson_darling_test.html
> 
> Some of the images are broken

Would you mention these images plz, If you mean the 3 tables distribution images at the end of the file, these images are already low in the original docx word file, they are attached as a image in the word original file like that (broken), you can Check them and compare. And if you mean other images plz inform me.

**Comment by ayushrana182** [comment]
Hi @HadeerAIA the list of broken images are:
_static/images/anderson_darling_test/formula_1.pngformula
_static/images/anderson_darling_test/table_1.pngformula
_static/images/anderson_darling_test/table_2.pngformula
_static/images/anderson_darling_test/formula_2.pngformula
_static/images/anderson_darling_test/formula_3.pngformula
_static/images/anderson_darling_test/formula_4.pngformula
_static/images/anderson_darling_test/formula_5.pngformula
_static/images/anderson_darling_test/table_4.pngformula
_static/images/anderson_darling_test/formula_6.pngformula
_static/images/anderson_darling_test/formula_8.pngformula
_static/images/anderson_darling_test/formula_9.pngformula
_static/images/anderson_darling_test/table_5.pngformula
_static/images/anderson_darling_test/formula_10.pngformula
_static/images/anderson_darling_test/formula_11.pngformula
_static/images/anderson_darling_test/table_6.pngformula
_static/images/anderson_darling_test/table_7.pngformula
_static/images/anderson_darling_test/formula_12.pngformula
_static/images/anderson_darling_test/formula_13.pngformula
_static/images/anderson_darling_test/table_9.pngformula
_static/images/anderson_darling_test/table_8.pngformula
_static/images/anderson_darling_test/table_10.pngformula

I think you have mistakes on the file path name and it is also missing the "About the Author" Section

**Comment by HadeerAIA** [comment]
> 

Ok I see, I figure out where is the problem and will fix it right now , but about the author section it wasn't including on my docx file

**Comment by HadeerAIA** [comment]
Would you check the images again I have fixed it @ayushrana182  @jbampton

**Review by jbampton — APPROVED** [review]

**Pull request merged**
