### PR TITLE
added a lite option to remove content

### PR DESCRIPTION
**Pull request by Dxuian**
in reference to #2393 
added a discard content boolean option

### CODE REVIEW

**Comment by BaseMax** [comment]
Hey, John need to take a look and review your merge request. He will it soon but not today.

Thank you so much for your contribute. Feel free to improve it as much as you can. John is a special man.

**Comment by BaseMax** [comment]
Hi there, happy to see you are helping to the project. It's great.

You need to do some changes, then we can approve and merge your changes.

You needs to remove "content" from the results array.  you has the test for the "lite" version. Lite version does not include content. It is not the best approach but helps and we can modify later. Can you please results array needs no content for the lite version?

**Comment by Dxuian** [comment]
> Hi there, happy to see you are helping to the project. It's great.
> 
> You need to do some changes, then we can approve and merge your changes.
> 
> You needs to remove "content" from the results array. you has the test for the "lite" version. Lite version does not include content. It is not the best approach but helps and we can modify later. Can you please results array needs no content for the lite version?

as asked ive removed content from the new code and enhanced the old code please review and merge

**Comment by BaseMax** [comment]
Thanks.

**Comment by Dxuian** [comment]
@jbampton please review and merge 🙏🙏🙏

**Comment by johnbampton** [comment]
Thanks and well done.

I tested locally and it seems to work fine.

Ready for approval and then merge

**Review by BaseMax — APPROVED** [review]
LGTM - from John

**Comment by BaseMax** [comment]
Many thanks and well done

**Pull request merged**
