### PR TITLE
Renamed Lime to Lima

### PR DESCRIPTION
**Pull request by Pritam0077**

### CODE REVIEW

**Review by jbampton — CHANGES_REQUESTED** [review]
Can you please rename the images properly ?

**Comment by Pritam0077** [comment]
Done

**Comment by jbampton** [comment]
> Can you please rename the images properly ?

`image-1` etc does not describe the image

**Comment by BaseMax** [comment]
> > Can you please rename the images properly ?
> 
> `image-1` etc does not describe the image

thanks john for your review.

**Pull request closed without merging**
