### PR TITLE
Saragossa

### PR DESCRIPTION
**Pull request by smriad**

### CODE REVIEW

**Review by jbampton — CHANGES_REQUESTED** [review]
You have both `.jpg` and `.jpeg`

**Comment by jbampton** [comment]
Screen Shot 2022-10-01 at 6 50 21 am

**Review by jbampton — CHANGES_REQUESTED** [review]
I think the image files should be name correctly

**Comment by smriad** [comment]
> I think the image files should be name correctly

jpeg renamed to jpg

**Comment by jbampton** [comment]
I mean not like `image1` but the real name of the image etc

**Comment by smriad** [comment]
> I mean not like `image1` but the real name of the image etc

updated

**Review by jbampton — APPROVED** [review]

**Pull request merged**
