### PR TITLE
Add restlyed workflow with GitHub Actions

### LINKED ISSUE #2797: Migrate Restyled to GitHub Actions
https://docs.restyled.io/docs/migrating-to-github-actions/

### PR DESCRIPTION
**Pull request by krishh-konar**
This PR adds restyle workflow that's triggered on pull requests.
Fixes #2797 

refs #344

### CODE REVIEW

**Comment by krishh-konar** [comment]
@jbampton  Seems like some tests are failing, but are unrelated to the changes made by this PR.

I have tested this in my own fork and the [restlye tests](https://github.com/krishh-konar/slurp/pull/1) are passing (the yaml lint checks and the restyle workflow itself).

**Comment by jbampton** [comment]
Testing

**Review by defihook — COMMENTED** [review]
base: ${{ steps.restyler.outputs.restyled-base }}

**Comment by BaseMax** [comment]
@jbampton check

**Review by jbampton — APPROVED** [review]

**Comment by jbampton** [comment]
Thank you !!

**Pull request merged**
