### PR TITLE
Added Aruba md file #1836

### PR DESCRIPTION
**Pull request by Vishrut19**
Added Aruba md file #1836 

I have added Aruba md file and added pictures also.

### CODE REVIEW

**Comment by Vishrut19** [comment]
Please review the changes and let me know if there is any need to do changes then I will do it.

**Review by jbampton — COMMENTED** [review]
You need to remove the `.DS_Store` file.

You can add that to your global gitignore

**Comment by jbampton** [comment]
You need to have lowercase filenames

Screen Shot 2022-10-05 at 9 05 48 pm

**Review by jbampton — CHANGES_REQUESTED** [review]
You need to add a menu link for `aruba.md` in `index.rst`

https://github.com/slurpcode/slurp/blob/main/doc/source/index.rst

**Pull request closed without merging**
