### PR TITLE
Make all the line standardized.Change all the lines to "About the Author"

### PR DESCRIPTION
**Pull request by ihasidul**
Worked on Issue #1562: Docs need standardization

### CODE REVIEW

**Review by smriad — APPROVED** [review]

**Review by jbampton — APPROVED** [review]

**Comment by BaseMax** [comment]
thanks

**Comment by smriad** [comment]
Good shot in opening ball @ihasidul

**Comment by ihasidul** [comment]
Thanks for the from you guys. I am enjoying the learning experience.

**Comment by jbampton** [comment]
Thank you !!

**Pull request merged**
